[package]
name = "demeter"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
colored = "2.0"
regex = "1.5"
pavao = "0.2"


[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"